project:
  type: book
  output-dir: docs
book:
  title: "Electromagnetism"
  author: "Claire Greenland"
  date: "03/25/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - testFile.qmd
    - electrostatics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



