# Lecture 3: Work and Energy in Electrostatics

*Recommended reading*: Griffiths Section 2.4

## Work done to move a charge

## Energy of a point charge distribution 

## Energy of a continuous charge distribution 

10. Work and Energy in Electrostatics
The work done to assemble a system of charges is related to the potential energy stored in the system. For point charges, the electrostatic potential energy $U$ is given by: 

11. Energy Density of the Electric Field

The energy density uuu of the electric field is: u=12ϵ0E2u = \frac{1}{2} \epsilon_0 E^2u=21ϵ0E2 where ϵ0\epsilon_0ϵ0 is the permittivity of free space.
The total electrostatic energy stored in a volume VVV is: U=12ϵ0∫VE2 d3rU = \frac{1}{2} \epsilon_0 \int_V E^2 \, d^3rU=21ϵ0∫VE2d3r

## Work and the electric dipole

## Post-lecture problem

As discussed in the lecture, consider a collection of 3 charges that form 3 sides of a square, as shown: 

[Get Fig 2.41 (??) from the Griffiths.]

In the lecture, we calculated the amount of work it takes to bring in a 4th charge $+q$ from far away and place it in the 4th corner of the square.
Now, your task is to calculate the total work it takes to assemble all 4 charges. 